RedHatInsights/platform-changelog-go

cmd/api/main.go, internal/config/services.yaml, internal/db/queries.go, internal/endpoints/commits.go, internal/endpoints/deploys.go, internal/endpoints/github.go, internal/endpoints/metrics.go, internal/endpoints/services.go, internal/metrics/metrics.go
Add a whole bunch of metrics for the endpoints and db operations
=> Add metrics

Dockerfile, build/Containerfile, development/compose.yml
Add a containerfile and compose
The compose needs a bit of work, but need to get it out there
=> Build stuff

Makefile, README.md
Add a webhook test to the makefile and add instructions to the README on
how to use it
Signed-off-by: Stephen Adams <tsadams@gmail.com>
=> Update readme and makefile

Makefile, cmd/api/main.go, go.mod, go.sum, internal/config/config.go, internal/config/services.yaml, internal/endpoints/github.go, internal/endpoints/gitlab.go, tests/gitlab_webhook.json
Hi, need review help on this
When tested the same way as github, msg "The service is not registered" shows up. We need the "ok" message to come up. The issue is most probably with ping event. Github has an event known as pingevent when a webhook is added to the repo, but I have not been able to find a similar one for gitlab - so I created one. But I think it's not right, which is why it doesn't work properly.
=> added gitlab webhook file

README.md
I had to add -B to get this to work. If this is something related to my specific setup, I understand, but I believe Stephen also had to do this.
=> Add -B to make build command

internal/db/queries.go
```services.Deploys = []models.Deploys{}return result, service```
=> Fixed an incorrect line

internal/db/queries.go
This makes sure that the gitlab url is added into the db for gitlab repos
Signed-off-by: Stephen Adams <stephen.adams@redhat.com>
=> [fix] make sure gitlab repos are loaded into the db

internal/db/commits.go, internal/db/deploys.go, internal/db/timelines.go, internal/models/models.go
- Added the order clause to newer api endpoints.
- Updated the service model with the proper foreign key (serviceId instead of id).
=> Added back sorting, updated foreignkey.

LICENSE
Add the apache 2.0 License to the project
Signed-off-by: Stephen Adams <stephen.adams@redhat.com>
=> Add the apache 2.0 license

internal/db/commits.go, internal/db/db.go, internal/db/deploys.go, internal/db/services.go, internal/db/timelines.go, internal/endpoints/commits.go, internal/endpoints/deploys.go, internal/endpoints/services.go, internal/endpoints/timelines.go, internal/endpoints/utils.go, internal/structs/structs.go, schema/openapi.yaml
Modeled after payload-tracker
* Added query struct in case the parameters get somehow more complicated.
* Added page and limit vars
[RHCLOUD-20560](https://issues.redhat.com/browse/RHCLOUD-20560)
=> Network Pagination with Page and Limit vars

internal/db/commits.go, internal/db/deploys.go, internal/db/timelines.go, internal/models/models.go, internal/structs/structs.go
Specifying an offset higher than the number of items returned all items.
Scan doesn't work 100% with offset and limit, so:
* Removed structs.TimelinesData
* Changed all of them to models.Timelines
* Made models.Timelines json omitempty
* Replaced Scan with find
=> [fix] Removed structs.TimelinesData and Scans

schema/openapi.yaml
The old api schema wasn't accurate, so this refines it. It should
correctly match what we respond with now
Signed-off-by: Stephen Adams <stephen.adams@redhat.com>
=> [schema] Update API schema

build/Containerfile
Signed-off-by: Brandon Schneider <bschneid@redhat.com>
=> Update these locations

build_deploy.sh, deployment/clowdapp.yml, pr_check.sh
- Added the build_deploy and pr_check scripts.
- Changed naming in the clowdapp.yaml.
=> More CI/CD

Makefile
Corrected missing $ for referencing var :)
Going to go ahead and merge since its so simple
=> [fix] Makefile typo

internal/db/commits.go, internal/db/db.go, internal/db/deploys.go, internal/db/services.go, internal/db/timelines.go, internal/db/types.go, internal/endpoints/services.go, internal/endpoints/utils.go, internal/structs/structs.go, schema/openapi.yaml
* Added filtering by service fields, particularly useful one being by tenant.
=> [RHCLOUD-20425] Filtering on Services endpoints

internal/config/config.go, internal/db/db.go
For error ```[error] failed to initialize database, got error failed to connect to `host=platform-changelog-stage.cm3mmfyi8atf.us-east-1.rds.amazonaws.com user=insights database=insights`: server error (FATAL: no pg_hba.conf entry for host "10.4.215.114", user "insights", database "insights", SSL off (SQLSTATE 28000))```
=> Added SSL as config option

deployment/clowdapp.yml
Changed replica count to 3, removed unused var
[RHCLOUD-23018](https://issues.redhat.com/browse/RHCLOUD-23018)
=> [RHCLOUD-23018] Changed replica count

internal/config/types.go, internal/structs/structs.go, schema/openapi.yaml
Changed TimelinesData to properly reflect underlying struct, and corrected services/{}/timelines, services/{}/commits, and services/{}/deploys to use TimelinesData schema.
[RHCLOUD-23215](https://issues.redhat.com/browse/RHCLOUD-23215)
=> [RHCLOUD-23215] Correcting TimelinesData references

Makefile, deployment/clowdapp.yml, internal/config/config.go, internal/endpoints/github.go, internal/endpoints/gitlab.go
[JIRA](https://issues.redhat.com/browse/RHCLOUD-24412)
- Linked github and gitlab secrets from vault.
- Removed DEBUG.
- Cleaned up gitlab webhook, and it now reads the token from the header
=> Added the secrets, removed DEBUG variable

internal/endpoints/github.go
On missing token, throw invalid error
=> Missing secret error

dashboards/grafana-dashboard-platform-changelog-general.configmap.yaml
- Drafting this to complete the onboarding epic
- Added panels for:
- General request failure rate
- Pods restarting
- Webhook and Tekton success and failure rates
- CPU and Memory usage
=> Grafana Dashboard

dashboards/grafana-dashboard-platform-changelog-general.configmap.yaml, internal/metrics/metrics.go
=> Dashboard query fixes, renamed metrics

internal/endpoints/tekton.go, tests/tekton/missing_status.json, tests/tekton/missing_timestamp.json, tests/tekton/not_onboarded.json
I was _wondering_ why no deployments were getting validated.
=> Correcting app check

README.md
Just trying to cover how the app will be used on the platform, fill in some stuff I was avoiding.
=> Needed Readme Updates

internal/db/timelines.go, internal/models/models.go
Timelines was using wrong db ref; bad foreign key declaration
=> [BUG] Deployments showing up for every service

.github/workflows/security-workflow-template.yml
Added security scan to github action based on [Platform Security GitHub Workflow
](https://github.com/RedHatInsights/platform-security-gh-workflow#platform-security-github-workflow) repo.
Jira [RHCLOUD-27007](https://issues.redhat.com/browse/RHCLOUD-27007)
Add new script into the github workflow folder
Provide a way to scan the container in a convenient, automated, and reliable manner within their GitHub repository.
- https://github.com/RedHatInsights/secure-coding-checklist
=> Add security scan workflow

internal/db/fields.go
Status was not included on return (timelines endpoints).
=> Missing status field on return

internal/db/commits.go, internal/db/deploys.go, internal/db/errors.go, internal/db/projects.go, internal/db/projects_test.go, internal/db/services.go, internal/db/services_test.go, internal/db/timelines.go, internal/db/utils.go, internal/endpoints/github.go, internal/endpoints/github_webhook.go, internal/endpoints/gitlab_webhook.go, internal/endpoints/tekton.go
- Making the endpoints more concious of the notfound error
- separating out getServiceAndProject functions
=> Properly checking for ErrNoRows

deployment/clowdapp.yml
=> Changing back to the up command

deployment/clowdapp.yml
Cmitch helped delete the bad tables, changing migration back.
=> Migrate up

internal/migrate/migrate.go
Remove unnecessary step migrations
I want to trigger the jenkins job.
=> Cleaning up drop migration

cmd/server.go
They have this package where it strips the slash and uses the one that is in the sub.Get
=>  strip slashes to the rescure
